packages:
  - server
  - client
  - shared

storeDir: .pnpm-store

allowBuilds:
  better-sqlite3: true
  esbuild: true
  koffi: true

minimumReleaseAgeExclude:
  - react-dom@19.3.0
  - react@19.3.0
  - scheduler@0.28.0
