import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import type { ArtworkCandidatesResponse, CustomArtworkResponse, CustomArtwork } from 'shared';
import { api, authenticatedImageUrl } from '../lib/api.js';
import { Button, Input, Select } from '../design/primitives/index.js';
import { QueryState } from '../app/QueryState.js';
import { DangerAction, PosterProgress, seasonName, useAction } from './common.js';
export const imageSource = (url: string) => url.startsWith('/api/') ? authenticatedImageUrl(url) : url;
export function Artwork({ path, bound }: { path: string; bound: boolean }) {
  const query = useQuery({ queryKey: ['artwork', path], queryFn: ({ signal }) => api.get<ArtworkCandidatesResponse>('/api/artwork/candidates', { path }, signal), enabled: bound });
  return !bound ? <p>Match this title to browse and select artwork.</p> : <QueryState query={query} label="artwork">{data => <ArtworkPicker path={path} data={data} />}</QueryState>;
}
function ArtworkPicker({ path, data }: { path: string; data: ArtworkCandidatesResponse }) {
  const [slot, setSlot] = useState('poster'), [source, setSource] = useState('all'), [url, setUrl] = useState('');
  const action = useAction(), custom = useQuery({ queryKey: ['custom-artwork', path], queryFn: ({ signal }) => api.get<CustomArtworkResponse>('/api/artwork/custom', { folder_path: path }, signal) });
  const slots = [...new Set(['poster', 'background', 'banner', 'clearlogo', ...data.season_poster_progress.required_seasons.map(season => `season-${String(season).padStart(2, '0')}-poster`), ...Object.keys(data.candidates), ...data.selections.map(choice => choice.slot)])].filter(value => !value.startsWith('episode-thumb-'));
  const selected = data.selections.find(choice => choice.slot === slot), candidates = (data.candidates[slot] ?? []).filter(value => source === 'all' || value.provider === source);
  function choose(value: string) { void action.run(() => api.send('/api/artwork/select', { folder_path: path, slot, url: value }), 'Choice saved. Build to write artwork to the media folder.'); }
  return <><section className="panel"><h2>Season poster selections</h2><PosterProgress progress={data.season_poster_progress} /><p>Choose each season manually. Saved choices survive rebuilds. Files already on disk do not count as a choice.</p></section><div className="library-toolbar"><Select label="Artwork slot" value={slot} onChange={event => setSlot(event.target.value)}>{slots.map(value => <option key={value} value={value}>{/^season-/.test(value) ? seasonName(Number(value.split('-')[1])) : value[0]!.toUpperCase() + value.slice(1)}</option>)}</Select><Select label="Artwork provider" value={source} onChange={event => setSource(event.target.value)}><option value="all">All providers</option><option value="tvdb">TVDB</option><option value="tmdb">TMDB</option><option value="fanart">Fanart.tv</option></Select></div>{data.warnings.map(warning => <p role="status" key={warning}>{warning}</p>)}{action.feedback}
    <div className="artwork-grid"><button type="button" className="artwork-choice auto-choice" aria-pressed={!selected} disabled={action.busy} onClick={() => void action.run(() => api.send('/api/artwork/clear', { folder_path: path, slot }), slot.startsWith('season-') ? 'Season choice cleared. This season needs selection.' : 'Automatic artwork restored.')}><strong>{slot.startsWith('season-') ? 'No selection' : 'Auto'}</strong><span>{slot.startsWith('season-') ? 'No automatic season poster' : 'Use the provider default'}</span></button>{candidates.map(candidate => <button type="button" key={candidate.url} className="artwork-choice" aria-pressed={selected?.url === candidate.url} disabled={action.busy} onClick={() => choose(candidate.url)}><img loading="lazy" src={imageSource(candidate.thumb ?? candidate.url)} alt={`${candidate.provider.toUpperCase()} ${slot}`} /><span>{candidate.provider.toUpperCase()} · {candidate.language ?? 'No language'}<br />{candidate.width ?? '?'} × {candidate.height ?? '?'}</span></button>)}</div>{candidates.length === 0 && <p>No provider candidates for this slot and filter. Upload an image or add a URL below.</p>}
    {selected && !candidates.some(candidate => candidate.url === selected.url) && <section className="panel"><h3>Saved choice</h3><img className="saved-artwork" src={imageSource(selected.url)} alt="Saved artwork choice" /><p className="file-path">{selected.url}</p></section>}
    <section className="panel"><h2>Custom artwork</h2><form className="actions" onSubmit={event => { event.preventDefault(); void action.run(async () => { const item = await api.send<CustomArtwork>('/api/artwork/custom-url', { folder_path: path, slot, url }); await api.send('/api/artwork/select', { folder_path: path, slot, url: item.url }); setUrl(''); }, 'Custom URL saved and selected.'); }}><Input label="Image URL" type="url" required value={url} onChange={event => setUrl(event.target.value)} /><Button type="submit" disabled={action.busy}>Add and select URL</Button></form><Input label="Upload image" type="file" accept="image/jpeg,image/png,image/webp" disabled={action.busy} onChange={event => { const file = event.target.files?.[0]; if (!file) return; const form = new FormData(); form.set('folder_path', path); form.set('slot', slot); form.set('file', file); void action.run(async () => { const item = await api.upload<CustomArtwork>('/api/artwork/upload', form); await api.send('/api/artwork/select', { folder_path: path, slot, url: item.url }); }, 'Image uploaded and selected.'); event.target.value = ''; }} />
      <QueryState query={custom} label="custom artwork">{value => <div className="custom-artwork-list">{value.items.map(item => <article key={item.id}><button type="button" className="artwork-choice" aria-pressed={selected?.url === item.url} disabled={action.busy} onClick={() => choose(item.url)}><img loading="lazy" src={imageSource(item.url)} alt={`Custom ${item.slot}`} /><span>Use for this slot</span></button><DangerAction label="Delete custom image" description="Delete this asset and clear the saved choices listed in the preview." record={{ op: 'custom-delete', id: item.id }} /></article>)}</div>}</QueryState></section><details className="panel danger-zone"><summary>Reset artwork choices</summary><DangerAction label="Clear all saved artwork choices" description="Clear only the previewed choices. Uploaded image files remain available." record={{ op: 'artwork-clear', folder_path: path }} /></details>
  </>;
}
