import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link, useLocation, useSearchParams } from 'react-router';
import type { ItemDetailResponse, NfoExplanation, MatchSearchResponse, ItemKind, MetadataSource, BuildResponse } from 'shared';
import { api, authenticatedImageUrl } from '../lib/api.js';
import { Button, Input, Select, Dialog } from '../design/primitives/index.js';
import { QueryState } from '../app/QueryState.js';
import { useConfirm } from '../components/ConfirmDialog.js';
import { DangerAction, Status, date, useAction } from './common.js';
import { Artwork } from './Artwork.js';
import { Overrides } from './Overrides.js';
import { EpisodeMapper } from './EpisodeMapper.js';

export function Detail() {
  const [params] = useSearchParams(), location = useLocation(), path = params.get('path') ?? '', tab = params.get('tab') ?? 'overview';
  const query = useQuery({ queryKey: ['detail', path], queryFn: ({ signal }) => api.get<ItemDetailResponse>('/api/items/detail', { path }, signal) });
  return <QueryState query={query} label="item details">{data => <>
    <header className="page-heading"><div><Link className="back-link" to={(location.state as { back?: string } | null)?.back ?? (data.state ? `/libraries/${encodeURIComponent(data.state.library)}` : '/libraries')}>Back to library</Link><h1>{data.binding?.title || data.state?.title || path.split(/[\\/]/).pop()}</h1><p className="file-path">{path}</p></div><BuildButtons path={path} bound={!!data.binding} /></header>
    <nav className="view-tabs" aria-label="Item views">{['overview', 'overrides', 'artwork', 'episodes'].map(value => <Link key={value} to={`?${new URLSearchParams({ path, tab: value })}`} state={location.state} aria-current={tab === value ? 'page' : undefined}>{value[0]!.toUpperCase() + value.slice(1)}</Link>)}</nav>
    {tab === 'artwork' ? <Artwork path={path} bound={!!data.binding} /> : tab === 'overrides' ? <Overrides path={path} detail={data} /> : tab === 'episodes' ? <EpisodeMapper path={path} kind={data.binding?.kind ?? data.state?.kind ?? 'series'} bound={!!data.binding} /> : <Overview data={data} />}
  </>}</QueryState>;
}
function BuildButtons({ path, bound }: { path: string; bound: boolean }) {
  const action = useAction();
  return <div><div className="actions"><Button variant="primary" disabled={!bound || action.busy} onClick={() => void action.run(() => api.send<BuildResponse>('/api/build', { folder_path: path }), 'Build queued. Follow progress in Jobs.')}>Build NFOs</Button><Button disabled={!bound || action.busy} onClick={() => void action.run(() => api.send<BuildResponse>('/api/build', { folder_path: path, force: true }), 'Rebuild queued. Follow progress in Jobs.')}>Force rebuild</Button><Link to="/jobs">Jobs</Link></div>{action.feedback}</div>;
}
function Overview({ data }: { data: ItemDetailResponse }) {
  const [explain, setExplain] = useState(false), action = useAction(), confirm = useConfirm();
  const explanation = useQuery({ queryKey: ['explain', data.path], queryFn: ({ signal }) => api.get<NfoExplanation>('/api/items/nfo-explain', { path: data.path }, signal), enabled: explain, staleTime: 0 });
  const [tag, setTag] = useState('');
  return <><div className="detail-overview"><div className="detail-poster">{data.state?.poster_path ? <img src={authenticatedImageUrl('/api/artwork/file', { path: data.state.poster_path })} alt={`${data.binding?.title ?? 'Item'} poster`} /> : <div className="poster-placeholder">No poster selected</div>}</div><section className="panel"><h2>Local metadata</h2><Button variant="quiet" onClick={() => setExplain(true)} aria-label="Explain NFO status">{data.state && <Status status={data.state.nfo_status} />}<span>Why this status?</span></Button><dl className="connection-details"><dt>Videos</dt><dd>{data.state?.episode_count_local ?? 0}</dd><dt>Matched provider episodes</dt><dd>{data.provider_episode_count ?? 'Unavailable'}</dd><dt>Last built</dt><dd>{date(data.state?.last_built ?? null)}</dd><dt>Last scan</dt><dd>{date(data.state?.last_scanned ?? null)}</dd><dt>Binding</dt><dd>{data.binding ? `${data.binding.provider.toUpperCase()} ${data.binding.external_id}` : 'Not matched'}</dd></dl>
      {!!data.state?.orphan_count && <div role="status" className="notice">{data.state.orphan_count} orphan companions found. Review the sweep below.</div>}
      <div className="tag-list">{[...new Set([...data.tags.tvdb, ...data.tags.tmdb])].map(value => <span key={value}>{value}</span>)}{data.tags.custom.map(value => <Button key={value} variant="quiet" disabled={action.busy} onClick={() => void action.run(() => api.send(`/api/items/tags?${new URLSearchParams({ folder_path: data.path, tag: value })}`, undefined, 'DELETE'))}>Remove tag: {value}</Button>)}</div><form className="actions" onSubmit={event => { event.preventDefault(); void action.run(async () => { await api.send('/api/items/tags', { folder_path: data.path, tag }); setTag(''); }); }}><Input label="Custom tag" value={tag} onChange={event => setTag(event.target.value)} /><Button type="submit" disabled={!tag.trim() || action.busy}>Add tag</Button></form>{action.feedback}</section></div>
    <Matching key={JSON.stringify(data.binding)} data={data} />
    <details className="panel danger-zone"><summary>Item actions</summary><DangerAction label="Sweep orphan companions" description="Preview obsolete episode NFOs and thumbnails before removing them." endpoint="/api/items/orphans/sweep" request={{ folder_path: data.path }} /><DangerAction label="Wipe NFOs and artwork" description="Remove generated NFOs, artwork, thumbnails and actor portraits. Keep media and recovery sidecar." endpoint="/api/items/clean" request={{ folder_path: data.path, keep_sidecar: true }} /><Button disabled={action.busy} className="danger-button" onClick={() => void action.run(async () => { if (!await confirm({ title: 'Remove item from app?', body: <p>Forget app records for {data.path}. Files and sidecar remain; a later scan can restore the item.</p>, action: 'Remove item' })) return false; await api.send('/api/items/remove', { folder_path: data.path }); })}>Remove item from app</Button></details>
    <Dialog open={explain} onClose={() => setExplain(false)} title="Why this NFO status?"><QueryState query={explanation} label="NFO explanation">{value => <><Status status={value.status} /><ul>{value.reasons.map(reason => <li key={reason}>{reason}</li>)}</ul>{value.seasons.map(season => <section key={season.folder}><h3>{season.season === null ? 'Root videos' : `Season ${season.season}`}</h3><p>{season.nfo_count}/{season.video_count} NFOs; {season.foreign_nfo_count} foreign</p>{season.missing.length > 0 && <p>Missing: {season.missing.join(', ')}</p>}{season.foreign.length > 0 && <p>Foreign: {season.foreign.join(', ')}</p>}</section>)}<p>{value.orphan_count} orphan companions</p></>}</QueryState></Dialog>
  </>;
}
function Matching({ data }: { data: ItemDetailResponse }) {
  const libraries=useQuery({queryKey:['libraries'],queryFn:({signal})=>api.libraries(signal)});
  const [chosenProvider,setProvider]=useState<MetadataSource>(), [kind, setKind] = useState<ItemKind>(data.binding?.kind ?? data.state?.kind ?? 'series');
  const provider=chosenProvider??(data.binding?.provider==='tmdb'||data.binding?.provider==='tvdb'?data.binding.provider:libraries.data?.libraries.find(library=>library.name===(data.state?.library??data.path.split(/[\\/]/).at(-2)))?.effective_metadata_source??'tvdb');
  const [search, setSearch] = useState(data.binding?.title ?? data.state?.title ?? ''), [submitted, setSubmitted] = useState(''), [id, setId] = useState(data.binding?.provider==='imdb'?'':data.binding?.external_id ?? ''), [locked, setLocked] = useState(data.binding?.source_locked ?? true);
  const [secondaryProvider, setSecondaryProvider] = useState<MetadataSource>(data.binding?.secondary_provider ?? (provider === 'tvdb' ? 'tmdb' : 'tvdb')), [secondaryId, setSecondaryId] = useState(data.binding?.secondary_external_id ?? '');
  const [secondarySearch, setSecondarySearch] = useState(''), [secondaryTerm, setSecondaryTerm] = useState('');
  const action = useAction(), confirm = useConfirm();
  const results = useQuery({ queryKey: ['match', submitted, provider, kind], queryFn: ({ signal }) => api.get<MatchSearchResponse>('/api/match/search', { q: submitted, provider, type: kind }, signal), enabled: !!submitted });
  const secondaryResults = useQuery({ queryKey: ['match-secondary', secondaryTerm, secondaryProvider, kind], queryFn: ({ signal }) => api.get<MatchSearchResponse>('/api/match/search', { q: secondaryTerm, provider: secondaryProvider, type: kind }, signal), enabled: !!secondaryTerm });
  return <section className="panel"><h2>{data.binding ? 'Metadata source' : 'Match this title'}</h2><div className="form-grid"><Select label="Provider" value={provider} onChange={event => { setProvider(event.target.value as MetadataSource); setId(''); }}><option value="tvdb">TVDB</option><option value="tmdb">TMDB</option></Select><Select label="Title type" value={kind} onChange={event => setKind(event.target.value as ItemKind)}><option value="series">TV series</option><option value="movie">Movie</option></Select><Input label="Provider ID" value={id} onChange={event => setId(event.target.value)} /><label><input type="checkbox" checked={locked} onChange={event => setLocked(event.target.checked)} /> Lock this source</label></div><div className="actions"><Button disabled={!id.trim() || action.busy} onClick={() => void action.run(() => api.send(data.binding ? '/api/match/source' : '/api/match/bind', data.binding ? { folder_path: data.path, provider, external_id: id, locked, kind } : { folder_path: data.path, provider, external_id: id, lock_source: locked, kind }))}>Save source</Button><Button disabled={action.busy} onClick={() => void action.run(() => api.send('/api/match/auto-bulk', { folder_paths: [data.path], only_unmatched: true }), 'Auto-match finished.')}>Auto-match</Button>{data.binding && <Button className="danger-button" disabled={action.busy} onClick={() => void action.run(async () => { if (!await confirm({ title: 'Unbind this item?', body: <p>Clear {data.binding!.provider.toUpperCase()} {data.binding!.external_id} from {data.path} and its recovery sidecar. Media stays on disk.</p>, action: 'Unbind' })) return false; await api.send(`/api/match/unbind?${new URLSearchParams({ folder_path: data.path })}`); })}>Unbind</Button>}</div>
    <form className="actions" onSubmit={event => { event.preventDefault(); setSubmitted(search.trim()); }}><Input label="Search provider titles" value={search} onChange={event => setSearch(event.target.value)} /><Button type="submit" disabled={!search.trim()}>Search</Button></form>{submitted && <QueryState query={results} label="matching titles">{value => <ul className="search-results">{value.results.length === 0 && <li>No matches found.</li>}{value.results.map(item => <li key={`${item.provider}:${item.id}`}><div><strong>{item.title} {item.year && `(${item.year})`}</strong><p>{item.plot}</p></div><Button disabled={action.busy} onClick={() => void action.run(() => api.send('/api/match/bind', { folder_path: data.path, provider: item.provider, external_id: item.id, kind: item.kind, title: item.title, year: item.year, lock_source: locked }))}>Bind {item.id}</Button></li>)}</ul>}</QueryState>}
    {data.binding && <details><summary>Secondary source</summary><p>Pin the other provider’s ID for artwork and NFO IDs.</p><div className="form-grid"><Select label="Secondary provider" value={secondaryProvider} onChange={event => setSecondaryProvider(event.target.value as MetadataSource)}><option value="tvdb">TVDB</option><option value="tmdb">TMDB</option></Select><Input label="Secondary provider ID" value={secondaryId} onChange={event => setSecondaryId(event.target.value)} /></div><Button disabled={action.busy} onClick={() => void action.run(() => api.send('/api/match/secondary', { folder_path: data.path, provider: secondaryId.trim() ? secondaryProvider : null, external_id: secondaryId.trim() || null }))}>Save secondary source</Button><form className="actions" onSubmit={event => { event.preventDefault(); setSecondaryTerm(secondarySearch.trim()); }}><Input label="Search secondary source" value={secondarySearch} onChange={event => setSecondarySearch(event.target.value)} /><Button type="submit" disabled={!secondarySearch.trim()}>Search secondary</Button></form>{secondaryTerm && <QueryState query={secondaryResults} label="secondary titles">{value => <ul>{value.results.map(item => <li key={item.id}><Button onClick={() => setSecondaryId(item.id)}>{item.title} ({item.year ?? 'Unknown year'}) · {item.id}</Button></li>)}</ul>}</QueryState>}</details>}{action.feedback}</section>;
}
