import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link, useLocation, useSearchParams } from 'react-router';
import type { Item, LibraryListEntry as LibraryInfo, ItemsQuery, AutoBulkResponse, BuildBulkResponse, BrowseResponse } from 'shared';
import { api, authenticatedImageUrl } from '../lib/api.js';
import { Badge, Button, Select, Input, TableWrapper } from '../design/primitives/index.js';
import { QueryState } from '../app/QueryState.js';
import { DangerAction, Status, PosterProgress, itemUrl, useAction } from './common.js';

type ViewState = { view: string; sort: string; status: string; q: string; posters: string };
const initial: ViewState = { view: 'grid', sort: 'title', status: 'all', q: '', posters: 'all' };
function saved(name: string): ViewState { try { return { ...initial, ...JSON.parse(localStorage.getItem(`library:${name}`) ?? '{}') }; } catch { return initial; } }
export function Library({ library }: { library: LibraryInfo }) {
  const name = library.name, location = useLocation(), [params, setParams] = useSearchParams();
  const [state, setState] = useState<ViewState>(() => ({ ...saved(name), ...Object.fromEntries([...params].filter(([key]) => key in initial)) }));
  const [search, setSearch] = useState(state.q), [filters, setFilters] = useState(false);
  const action = useAction(), restored = useRef(false), scroll = useRef(0);
  function update(patch: Partial<ViewState>) { const next = { ...state, ...patch }; setState(next); setParams(next, { replace: true }); }
  useEffect(() => { const timer = setTimeout(() => { if (state.q !== search) update({ q: search }); }, 300); return () => clearTimeout(timer); }, [search, state]);
  useEffect(() => { try { localStorage.setItem(`library:${name}`, JSON.stringify(state)); } catch { /* View state still works without storage. */ } }, [name, state]);
  const request: ItemsQuery = { library: name, ...(state.q ? { q: state.q } : {}), ...(state.status === 'complete' ? { status: 'complete' } : state.status === 'needs' ? { hide_organized: true } : {}), ...(state.posters !== 'all' ? { poster_selection: state.posters as ItemsQuery['poster_selection'] } : {}) };
  const query = useQuery({ queryKey: ['items', name, request], queryFn: ({ signal }) => api.items(request, signal) });
  useLayoutEffect(() => {
    if (!query.data || restored.current) return;
    restored.current = true;
    try { window.scrollTo(0, Number(sessionStorage.getItem(`scroll:${name}`) ?? 0)); } catch { /* Storage may be disabled. */ }
  }, [query.data, name]);
  useLayoutEffect(() => { const remember = () => { scroll.current = window.scrollY; try { sessionStorage.setItem(`scroll:${name}`, String(scroll.current)); } catch { /* Scroll remains usable. */ } }; window.addEventListener('scroll', remember); return () => window.removeEventListener('scroll', remember); }, [name]);
  function sorted(items: Item[]) { return [...items].sort((a, b) => state.sort === 'added' ? b.date_added - a.date_added : state.sort === 'updated' ? (b.date_updated ?? 0) - (a.date_updated ?? 0) : state.sort === 'seasons' ? b.season_count_local - a.season_count_local : (state.sort === 'title-desc' ? -1 : 1) * (a.sort_title ?? a.title ?? '').localeCompare(b.sort_title ?? b.title ?? '', undefined, { sensitivity: 'base' })); }
  return <>
    <header className="page-heading"><div><Link className="back-link" to="/libraries">All libraries</Link><h1>{name}</h1><p>{library.kind === 'movies' ? 'Movie collection' : 'Series collection'} · {library.effective_metadata_source.toUpperCase()}</p></div><div className="actions"><Button disabled={action.busy} onClick={() => void action.run(() => api.send(`/api/libraries/${encodeURIComponent(name)}/scan`), 'Scan scheduled. Refresh titles to see new results.')}>Scan library</Button><Button onClick={() => void query.refetch()} disabled={query.isFetching}>Refresh titles</Button></div></header>
    <div className="library-toolbar"><Input label="Search titles" value={search} onChange={event => setSearch(event.target.value)} type="search" placeholder="Find a title…" /><Select label="NFO status" value={state.status} onChange={event => update({ status: event.target.value })}><option value="all">All</option><option value="needs">Needs work</option><option value="complete">Complete</option></Select><Select label="Sort" value={state.sort} onChange={event => update({ sort: event.target.value })}><option value="title">Title A–Z</option><option value="title-desc">Title Z–A</option><option value="added">Date added</option><option value="updated">Date updated</option><option value="seasons">Season count</option></Select><div className="segmented" aria-label="Library view"><Button aria-pressed={state.view === 'grid'} onClick={() => update({ view: 'grid' })}>Grid</Button><Button aria-pressed={state.view === 'list'} onClick={() => update({ view: 'list' })}>List</Button></div><Button aria-expanded={filters} aria-controls="library-filters" onClick={() => setFilters(!filters)}>Filters</Button></div>
    {filters && <section id="library-filters" className="panel filter-panel" aria-label="Library filters"><Select label="Season posters" value={state.posters} onChange={event => update({ posters: event.target.value })}><option value="all">All</option><option value="needs_selection">Needs selection</option><option value="selected">Selected</option></Select><p>Progress counts saved manual choices for seasons with local videos. Adding a season can return a show to needs selection.</p><details><summary>Selection details</summary>{query.data?.items.filter(item => item.kind === 'series').map(item => <div key={item.folder_path}><strong>{item.title}</strong>{item.season_poster_progress ? <PosterProgress progress={item.season_poster_progress} /> : <p>Progress unavailable; selection needs review.</p>}</div>)}</details></section>}
    <div className="actions collection-actions"><Button disabled={action.busy} onClick={() => void action.run(() => api.send<AutoBulkResponse>('/api/match/auto-bulk', { library: name, only_unmatched: true }), 'Auto-match finished.')}>Auto-match all</Button><Button variant="primary" disabled={action.busy} onClick={() => void action.run(() => api.send<BuildBulkResponse>('/api/build/bulk', { library: name, only_unbuilt: true }), 'Builds queued. Follow progress in Jobs.')}>Build all needing work</Button></div>{action.feedback}
    <QueryState query={query} label="titles">{({ items }) => <><p className="collection-count">{items.length} {items.length === 1 ? 'title' : 'titles'}</p>{items.length === 0 ? <div className="empty-state"><h2>No titles found</h2><p>Adjust filters or scan this library to find local titles.</p></div> : state.view === 'grid' ? <ul className="poster-grid">{sorted(items).map(item => <li key={item.folder_path}><Link className="poster-card" to={itemUrl(item.folder_path)} state={{ back: location.pathname + location.search }}><div className="poster-frame">{item.poster_path ? <img loading="lazy" src={authenticatedImageUrl('/api/artwork/file', { path: item.poster_path })} alt="" /> : <span className="poster-placeholder" aria-hidden="true">{(item.title ?? '?').slice(0, 1)}</span>}<span className="poster-status"><Status status={item.nfo_status} /></span></div><strong>{item.title || item.folder_path.split(/[\\/]/).pop()}</strong><span className="muted">{item.year ?? 'Year unknown'} · {item.kind === 'movie' ? 'Movie' : `${item.episode_count_local} videos`}</span></Link></li>)}</ul> : <TableWrapper label={`${name} titles`}><table><thead><tr><th>Title</th><th>NFO status</th><th>Media</th><th>Source</th></tr></thead><tbody>{sorted(items).map(item => <tr key={item.folder_path}><th scope="row"><Link to={itemUrl(item.folder_path)} state={{ back: location.pathname + location.search }}>{item.title || item.folder_path.split(/[\\/]/).pop()}</Link></th><td><Status status={item.nfo_status} /></td><td>{item.episode_count_local} videos<span className="item-subtitle">{item.season_count_local} seasons</span></td><td>{item.provider?.toUpperCase() ?? 'Unbound'}</td></tr>)}</tbody></table></TableWrapper>}</>}</QueryState>
    <details className="panel library-options"><summary>Library options</summary><div className="form-grid"><Select label="Metadata provider" value={library.metadata_source ?? ''} disabled={action.busy} onChange={event => void action.run(() => api.send(`/api/libraries/${encodeURIComponent(name)}`, { metadata_source: event.target.value || null }))}><option value="">Global default</option><option value="tvdb">TVDB</option><option value="tmdb">TMDB</option></Select><Select label="Library kind" value={library.kind} disabled={action.busy} onChange={event => void action.run(() => api.send(`/api/libraries/${encodeURIComponent(name)}`, { kind: event.target.value }))}><option value="tv">TV series</option><option value="movies">Movies</option><option value="mixed">Mixed</option></Select><label><input type="checkbox" checked={!!library.enabled} disabled={action.busy} onChange={event => void action.run(() => api.send(`/api/libraries/${encodeURIComponent(name)}`, { enabled: event.target.checked }))} /> Enabled</label></div><Badge>{library.enabled ? 'Enabled' : 'Disabled'}</Badge></details>
    <details className="panel danger-zone"><summary>Danger Zone</summary><DangerAction label="Sweep orphan companions" description="Remove NFOs and thumbnails without matching videos." endpoint={`/api/libraries/${encodeURIComponent(name)}/orphans/sweep`} request={{ library: name }} /><DangerAction label="Wipe NFOs and artwork" description="Remove generated metadata and artwork. Media and sidecars stay." endpoint={`/api/libraries/${encodeURIComponent(name)}/wipe-nfo`} request={{ library: name, keep_sidecar: true }} /><DangerAction label="Delete every sidecar" description="Remove recovery sidecars. Existing NFOs, artwork and media stay." endpoint={`/api/libraries/${encodeURIComponent(name)}/wipe-sidecars`} request={{ library: name }} /><DangerAction label="Prune missing folders" description="Forget tracked folders that are no longer on disk." endpoint="/api/items/prune" request={{ library: name }} /><DangerAction label="Prune empty folders" description="Forget folders with no videos. Leave their files on disk." endpoint="/api/items/prune-empty" request={{ library: name, delete_files: false }} /><DangerAction label="Remove library from app" description="Forget this library and its app records. Media and recovery sidecars stay on disk." record={{ op: 'library-delete', library: name }} /></details>
  </>;
}
export function FolderBrowser() {
  const [{path,depth}, setFolder] = useState({path:'',depth:0}), [open,setOpen] = useState(false);
  const query = useQuery({ queryKey: ['browse', path], queryFn: ({ signal }) => api.get<BrowseResponse>('/api/browse', path ? { path } : {}, signal), enabled:open });
  return <details className="panel" onToggle={event=>setOpen(event.currentTarget.open)}><summary>Browse media folders</summary>{open&&<QueryState query={query} label="folders">{data => <><p className="file-path">{data.path}</p>{data.parent && <Button onClick={() => setFolder({path:data.parent!,depth:depth-1})}>Parent folder</Button>}<ul className="folder-list">{data.items.filter(item => item.is_dir).map(item => <li key={item.path}><Button variant="quiet" onClick={() => setFolder({path:item.path,depth:depth+1})}>{item.name}</Button>{depth===1&&<Link to={itemUrl(item.path)}>Open item</Link>}</li>)}</ul></>}</QueryState>}</details>;
}
