import { useState } from 'react';
import type { RenameRequest, RenamePreview, RenameResult } from 'shared';
import { api } from '../lib/api.js';
import { Button, Input, Select, Badge, TableWrapper } from '../design/primitives/index.js';
import { useConfirm } from '../components/ConfirmDialog.js';
import { useAction } from './common.js';
export function Rename({ path }: { path: string }) {
  const [inputs, setInputs] = useState<RenameRequest>({ folder_path: path, series_type: 'auto', release_group: '', template: '', daily_template: '', anime_template: '' });
  const [preview, setPreview] = useState<RenamePreview | null>(null), [checked, setChecked] = useState<string[]>([]), [result, setResult] = useState<RenameResult | null>(null), action = useAction(), confirm = useConfirm();
  function update(patch: Partial<RenameRequest>) { setInputs({ ...inputs, ...patch }); setPreview(null); setResult(null); }
  return <section className="panel"><h2>Rename to scheme</h2><p>Preview video names and companions. Only checked moves apply. Changed files require a new preview.</p><div className="form-grid"><Select label="Series type" value={inputs.series_type} onChange={event => update({ series_type: event.target.value as RenameRequest['series_type'] })}><option value="auto">Auto</option><option value="standard">Standard</option><option value="daily">Daily</option><option value="anime">Anime</option></Select><Input label="Release group override" value={inputs.release_group} onChange={event => update({ release_group: event.target.value })} /><Input label="Template override" placeholder="Use saved template" value={inputs.template} onChange={event => update({ template: event.target.value })} /><Input label="Daily template override" placeholder="Use saved daily template" value={inputs.daily_template} onChange={event => update({ daily_template: event.target.value })} /><Input label="Anime template override" placeholder="Use saved anime template" value={inputs.anime_template} onChange={event => update({ anime_template: event.target.value })} /></div><Button disabled={action.busy} onClick={() => void action.run(async () => { const value = await api.send<RenamePreview>('/api/episodes/rename/preview', inputs); setPreview(value); setChecked(value.items.filter(item => !item.unchanged && !item.conflict).map(item => item.src)); setResult(null); }, 'Preview ready.')}>Preview rename</Button>{action.feedback}
    {preview && <><TableWrapper label="Rename preview"><table><thead><tr><th>Apply</th><th>Current name</th><th>New name</th><th>Status</th></tr></thead><tbody>{preview.items.map(item => <tr key={item.src}><td><input type="checkbox" aria-label={`Rename ${item.src_name}`} disabled={action.busy || item.unchanged || !!item.conflict} checked={checked.includes(item.src)} onChange={event => setChecked(event.target.checked ? [...checked, item.src] : checked.filter(src => src !== item.src))} /></td><td className="file-path">{item.src_name}</td><td className="file-path">{item.dst_name}{!!item.companions?.length && <details><summary>{item.companions.length} companions</summary><ul>{item.companions.map(move => <li key={move.src}>{move.src}<br />to {move.dst}</li>)}</ul></details>}</td><td>{item.conflict ? <Badge tone="warning">{item.conflict}</Badge> : item.unchanged ? 'Unchanged' : 'Ready'}</td></tr>)}</tbody></table></TableWrapper><Button variant="primary" disabled={action.busy || checked.length === 0} onClick={() => void action.run(async () => {
      if (!await confirm({ title: `Rename ${checked.length} videos?`, action: 'Apply checked renames', body: <><p>Move these videos and their previewed companions within their current folders.</p><ul className="preview-list">{preview.items.filter(item => checked.includes(item.src)).map(item => <li key={item.src}>{item.src_name}<br />to {item.dst_name} ({item.companions?.length ?? 0} companions)</li>)}</ul></> })) return false;
      try { setResult(await api.send<RenameResult>('/api/episodes/rename/apply', { folder_path: path, preview_id: preview.preview_id, confirm: true, only_src: checked })); } finally { setPreview(null); }
    }, 'Rename request finished.')}>Apply checked renames</Button></>}
    {result && <div role="status"><p>{result.renamed.length} videos renamed; {result.skipped.length} skipped; {result.failed.length} failed.</p><ul>{[...result.skipped, ...result.failed, ...result.companions_failed].map((item, index) => <li key={index}>{item.src}: {item.reason}</li>)}</ul></div>}
  </section>;
}
