import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router';
import type { WatcherStatus, WatcherEvent, WatcherReview, Schedule, ScheduleRequest, LibrariesResponse } from 'shared';
import { api } from '../lib/api.js';
import { Button, Input, Select, Badge, TableWrapper } from '../design/primitives/index.js';
import { QueryState } from '../app/QueryState.js';
import { useConfirm } from '../components/ConfirmDialog.js';
import { DangerAction, date, itemUrl, useAction } from './common.js';
export function Watcher() {
  const status = useQuery({ queryKey: ['watcher-status'], queryFn: ({ signal }) => api.get<WatcherStatus>('/api/watcher/status', {}, signal), refetchInterval: 5000 });
  const events = useQuery({ queryKey: ['watcher-events'], queryFn: ({ signal }) => api.get<{ events: WatcherEvent[] }>('/api/watcher/events', { limit: '100' }, signal), refetchInterval: 5000 });
  const review = useQuery({ queryKey: ['watcher-review'], queryFn: ({ signal }) => api.get<{ items: WatcherReview[] }>('/api/watcher/review', {}, signal), refetchInterval: 5000 });
  const action = useAction(), confirm = useConfirm();
  return <><header className="page-heading"><div><h1>Watcher</h1><p>New media, stable files, then matching and queued builds.</p></div></header><section className="panel"><QueryState query={status} label="watcher status">{value => <><div className="actions"><Badge tone={value.running ? 'success' : 'neutral'}>{value.running ? 'Watching' : 'Stopped'}</Badge><Button disabled={action.busy} onClick={() => void action.run(() => api.send('/api/watcher/toggle', { enabled: !value.enabled }))}>{value.enabled ? 'Disable watcher' : 'Enable watcher'}</Button></div><p>{value.pending_count} waiting · {value.in_flight_count} active · {value.debounce_seconds}s debounce</p><ul>{value.watched_paths.map(path => <li className="file-path" key={path}>{path}</li>)}</ul>{!value.enabled && <p>A server kill switch can override the enabled setting.</p>}</>}</QueryState>{action.feedback}</section><section className="panel"><h2>Needs review</h2><QueryState query={review} label="watcher review">{value => value.items.length === 0 ? <p>No items need review.</p> : <ul className="review-list">{value.items.map(item => <li key={item.folder_path}><Link to={itemUrl(item.folder_path)}>{item.folder_path.split(/[\\/]/).pop()}</Link><p>{item.reason}: {item.detail}</p><p>{item.attempts} attempts · {date(item.last_attempt_at)}</p><div className="actions"><Button disabled={action.busy} onClick={() => void action.run(() => api.send('/api/watcher/review/retry', { folder_path: item.folder_path }), 'Watcher pipeline re-armed.')}>Retry pipeline</Button><Button disabled={action.busy} onClick={() => void action.run(async () => { if (!await confirm({ title: 'Dismiss review entry?', body: <p>Remove the review entry for {item.folder_path}. Media remains unchanged.</p>, action: 'Dismiss' })) return false; await api.send('/api/watcher/review/resolve', { folder_path: item.folder_path }); })}>Dismiss</Button></div></li>)}</ul>}</QueryState><DangerAction label="Clear review queue" description="Remove the previewed review entries. New or updated entries are preserved." record={{ op: 'review-clear' }} /></section><section className="panel"><h2>Recent events</h2><QueryState query={events} label="watcher events">{value => <ul className="event-list">{value.events.length === 0 && <li>No recent events.</li>}{value.events.map((event, index) => <li key={index}><time>{date(event.timestamp)}</time><strong>{event.event_type}</strong><span>{event.message}</span><small className="file-path">{event.folder_path}</small></li>)}</ul>}</QueryState></section></>;
}
const actions = ['scan_only', 'match_only', 'build_only', 'match_and_build', 'full'] as const;
export function Schedules() {
  const query = useQuery({ queryKey: ['schedules'], queryFn: ({ signal }) => api.get<{ schedules: Schedule[] }>('/api/schedules', {}, signal), refetchInterval: 5000 });
  const libraries = useQuery({ queryKey: ['libraries'], queryFn: ({ signal }) => api.libraries(signal) });
  const [editing, setEditing] = useState<Schedule | null>(null), [creating, setCreating] = useState(false), action = useAction(), confirm = useConfirm();
  return <section className="panel"><h2>Schedules</h2><p>Five-field cron runs in UTC. A successful schedule can submit builds that finish later in Jobs.</p><Button onClick={() => { setEditing(null); setCreating(true); }}>Add schedule</Button><QueryState query={query} label="schedules">{data => <TableWrapper label="Schedules"><table><thead><tr><th>Library</th><th>Cron (UTC)</th><th>Action</th><th>Last run</th><th>Controls</th></tr></thead><tbody>{data.schedules.map(schedule => <tr key={schedule.id}><td>{schedule.library ?? 'All enabled libraries'}</td><td>{schedule.cron}<br />{schedule.enabled ? 'Enabled' : 'Disabled'}</td><td>{schedule.action}</td><td>{date(schedule.last_run)}<br />{schedule.last_status}: {schedule.last_message}</td><td><div className="actions"><Button onClick={() => { setEditing(schedule); setCreating(false); }}>Edit</Button><Button disabled={action.busy} onClick={() => void action.run(() => api.send(`/api/schedules/${schedule.id}/run`), 'Schedule started.')}>Run now</Button><Button className="danger-button" disabled={action.busy} onClick={() => void action.run(async () => { if (!await confirm({ title: 'Delete schedule?', body: <p>Delete {schedule.cron} UTC, {schedule.action}, for {schedule.library ?? 'all enabled libraries'}.</p>, action: 'Delete schedule' })) return false; await api.send(`/api/schedules/${schedule.id}`, undefined, 'DELETE'); })}>Delete</Button></div></td></tr>)}</tbody></table></TableWrapper>}</QueryState>{action.feedback}{(creating || editing) && <QueryState query={libraries} label="schedule libraries">{data => <ScheduleEditor key={editing?.id ?? 'new'} schedule={editing} libraries={data} done={() => { setEditing(null); setCreating(false); }} />}</QueryState>}</section>;
}
function ScheduleEditor({ schedule, libraries, done }: { schedule: Schedule | null; libraries: LibrariesResponse; done: () => void }) {
  const [value, setValue] = useState<ScheduleRequest>({ library: schedule?.library ?? null, cron: schedule?.cron ?? '0 3 * * *', action: schedule?.action ?? 'scan_only', enabled: schedule ? !!schedule.enabled : true }), action = useAction();
  return <form className="panel" onSubmit={event => { event.preventDefault(); void action.run(async () => { await api.send(schedule ? `/api/schedules/${schedule.id}` : '/api/schedules', value, schedule ? 'PATCH' : 'POST'); done(); }); }}><h3>{schedule ? 'Edit schedule' : 'New schedule'}</h3><div className="form-grid"><Select label="Scheduled library" value={value.library ?? ''} onChange={event => setValue({ ...value, library: event.target.value || null })}><option value="">All enabled libraries</option>{libraries.libraries.map(library => <option key={library.name}>{library.name}</option>)}</Select><Input label="Cron expression (UTC)" required value={value.cron} onChange={event => setValue({ ...value, cron: event.target.value })} /><Select label="Scheduled action" value={value.action} onChange={event => setValue({ ...value, action: event.target.value as ScheduleRequest['action'] })}>{actions.map(action => <option key={action}>{action}</option>)}</Select><label><input type="checkbox" checked={value.enabled} onChange={event => setValue({ ...value, enabled: event.target.checked })} /> Enabled</label></div><div className="actions"><Button type="submit" disabled={action.busy}>Save schedule</Button><Button disabled={action.busy} onClick={done}>Cancel edit</Button></div>{action.feedback}</form>;
}
